# Use a imagem base do Node.js 22
FROM node:22-alpine

# Configure variáveis de ambiente padrão
ENV NODE_ENV=development

# Instale dependências adicionais
RUN apk add --no-cache bash

# Defina o diretório de trabalho
WORKDIR /usr/src/app

# Copie os arquivos de dependências
COPY package*.json ./

# Instale todas as dependências (incluindo dev)
RUN npm install

# Copie o restante do projeto
COPY . .

# Exponha a porta padrão do NestJS
EXPOSE 3000

# Comando para iniciar a aplicação no modo dev
CMD ["npm", "run", "start:dev"]
